#General
server:
  context-path: /fibi
  port: 9090
  
#Security  
security:
  user:
    name: fibi
    password: fibi

#MongoDB
spring:
  data:
    mongodb:
      host: ds019866.mlab.com
      port: 19866
      database: fibi
      #uri: mongodb://ds019866.mlab.com:19866/fibi
      username: fibiuser
      password: fibiuser
      #uri: mongodb://localhost/fibi
      
      
#Logging
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO 
    org.springframework.data: DEBUG 
    
